apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
  - includeSelectors: false
    pairs:
      app.kubernetes.io/part-of: product-media

resources:
  - config/configmap.yaml
  - storage/nfs-server.yaml
  - storage/shared-volume.yaml
  - datastore/postgres.yaml
  - datastore/redis.yaml
  - api/deployment.yaml
  - api/service.yaml
  - api/migration-job.yaml
  - portal/deployment.yaml
  - portal/service.yaml
  - worker/deployment.yaml
  - ingress/ingress.yaml
