apiVersion: v1
kind: Service
metadata:
  name: portal
  labels:
    app.kubernetes.io/name: portal
    app.kubernetes.io/part-of: product-media
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: portal
  ports:
    - name: http
      port: 8080
      targetPort: http
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: portal
  labels:
    app.kubernetes.io/name: portal
    app.kubernetes.io/part-of: product-media
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: portal
